version: "3.8"

services:
  wex-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./data:/app/data
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "api.fiscaldata.treasury.gov:104.86.186.109"
    networks:
      - wex-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  wex-network:
    driver: bridge
